name: MTP-spider

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git
        run: |
          git config --global user.email "koi996@pm.me"
          git config --global user.name "hero866"

      - name: Run fetch and update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./getmtp
          ./getmtp

          # 拉取远程更改并自动合并
          git fetch origin main
          git reset --soft origin/main  # 强制同步到远程分支，但保留本地改动
          git add -A
          git commit -m "🚀 Proxies Updated - $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" || true

          # 强制推送
          git push origin main --force
